export const inputList = [
  {
    nameInput: "email",
    idInput: "email",
    typeInput: "email",
    placeholderInput: "exsample@mail.com",
    nameLabel: "E-mail",
    hintText: "Подсказка",
  },
  {
    nameInput: "password",
    idInput: "password",
    typeInput: "password",
    placeholderInput: "_",
    nameLabel: "Пароль",
    hintText: "Подсказка",
  },
  {
    nameInput: "tel",
    idInput: "tel",
    typeInput: "tel",
    placeholderInput: "+7 (900) 000-00-00",
    nameLabel: "Телефон",
    hintText: "Подзказка",
  },
  {
    nameInput: "fullName",
    idInput: "fullName",
    typeInput: "text",
    placeholderInput: "Константинопольский Константин Конст...",
    nameLabel: "ФИО",
    hintText: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    nameInput: "sberId",
    idInput: "sberId",
    typeInput: "text",
    placeholderInput: "",
    nameLabel: "Сбербанк ID",
    hintText: "Подсказка",
  },
]